server:
  port: 8080

database:
  host: localhost
  port: 3306
  user: root
  password: ""
  dbname: mem_test
  charset: utf8mb4

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

dify:
  base_url: http://dify.ickey.com.cn/v1
  api_key: app-4kBYdLfSFgL2HZ3NTeUYpdpL
  app_type: workflow
  response_mode: blocking
  # workflow 必填 inputs 字段名（通常就是 system/query）
  workflow_system_key: "system"
  workflow_query_key: "query"
  workflow_output_key: ""

